# Generated by Django 6.0.7 on 2026-10-06 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                ("client_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("info", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "MCP client",
            },
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                ("token_hash", models.CharField(max_length=64, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("code", "Code"), ("access", "Access")], max_length=6
                    ),
                ),
                ("data", models.JSONField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_unfold_agentic_layer.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP access token",
            },
        ),
    ]
