# Generated by Django 6.0.7 on 2026-10-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="attachment",
            field=models.FileField(blank=True, upload_to="attachments/"),
        ),
    ]
